#!/usr/bin/env bash
#
# Shows all 256 colors of xterm's 256-color mode.
#

color=0
while [ $color -lt 16 ]; do
    printf "%3d: \x1B[48;5;%dm        \x1B[0m " $color $color
    printf "%2d: \x1B[48;5;%dm        \x1B[0m " $[$color+1] $[$color+1]
    color=$[$color+2]
    if [ $[$color%8] -eq 0 ]; then echo; fi
done
while [ $color -lt 256 ]; do
    printf "%3d: \x1B[48;5;%dm            \x1B[0m " $color $color
    color=$[$color+1]
    if [ $[($color-16)%6] -eq 0 ]; then echo; fi
done
